# Generated by Django 6.1 on 2026-08-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('released', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('digital', 'Digital'), ('vinyl', 'Vinyl'), ('cd', 'CD')], default='digital', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'ordering': ['-released', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('duration_seconds', models.PositiveIntegerField(default=180)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.album')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
